services:
  - type: web
    name: bradesco-pix-monitor
    env: docker
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: bradesco-postgres
          property: connectionString
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"

databases:
  - name: bradesco-postgres
    databaseName: bradesco_pix
    user: postgres 